import type { DashboardStats, DuplicateTransaction, ScanHistory } from './types'

export function getMockDashboardStats(): DashboardStats {
  return {
    totalScans: 24,
    duplicatesFound: 156,
    duplicatesResolved: 142,
    moneySaved: 12450.75,
  }
}

export function getMockDuplicates(): DuplicateTransaction[] {
  return [
    {
      id: '1',
      vendorName: 'Office Supplies Co',
      description: 'Monthly office supplies order',
      amount: 234.50,
      transactionDate: '2024-01-15',
      transactionType: 'Bill',
      confidenceScore: 0.95,
      status: 'pending',
      groupId: 'g1',
    },
    {
      id: '2',
      vendorName: 'Office Supplies Co',
      description: 'Monthly office supplies order',
      amount: 234.50,
      transactionDate: '2024-01-15',
      transactionType: 'Bill',
      confidenceScore: 0.95,
      status: 'pending',
      groupId: 'g1',
    },
    {
      id: '3',
      vendorName: 'Cloud Hosting Inc',
      description: 'Server hosting - January',
      amount: 599.00,
      transactionDate: '2024-01-20',
      transactionType: 'Expense',
      confidenceScore: 0.88,
      status: 'pending',
      groupId: 'g2',
    },
    {
      id: '4',
      vendorName: 'Cloud Hosting Inc',
      description: 'Server hosting - Jan',
      amount: 599.00,
      transactionDate: '2024-01-20',
      transactionType: 'Expense',
      confidenceScore: 0.88,
      status: 'pending',
      groupId: 'g2',
    },
    {
      id: '5',
      vendorName: 'Marketing Agency LLC',
      description: 'Social media campaign Q1',
      amount: 1500.00,
      transactionDate: '2024-01-10',
      transactionType: 'Bill',
      confidenceScore: 0.92,
      status: 'kept',
      groupId: 'g3',
    },
    {
      id: '6',
      vendorName: 'Marketing Agency LLC',
      description: 'Social media campaign Q1',
      amount: 1500.00,
      transactionDate: '2024-01-10',
      transactionType: 'Bill',
      confidenceScore: 0.92,
      status: 'deleted',
      groupId: 'g3',
      resolvedAt: '2024-01-25',
    },
    {
      id: '7',
      vendorName: 'Insurance Provider',
      description: 'Business insurance premium',
      amount: 875.00,
      transactionDate: '2024-02-01',
      transactionType: 'Bill',
      confidenceScore: 0.78,
      status: 'pending',
      groupId: 'g4',
    },
    {
      id: '8',
      vendorName: 'Insurance Provider',
      description: 'Business insurance premium - Feb',
      amount: 875.00,
      transactionDate: '2024-02-01',
      transactionType: 'Bill',
      confidenceScore: 0.78,
      status: 'pending',
      groupId: 'g4',
    },
    {
      id: '9',
      vendorName: 'Utility Company',
      description: 'Electric bill - January',
      amount: 312.45,
      transactionDate: '2024-01-28',
      transactionType: 'Expense',
      confidenceScore: 0.85,
      status: 'ignored',
      groupId: 'g5',
    },
    {
      id: '10',
      vendorName: 'Utility Company',
      description: 'Electric bill - Jan',
      amount: 312.45,
      transactionDate: '2024-01-28',
      transactionType: 'Expense',
      confidenceScore: 0.85,
      status: 'ignored',
      groupId: 'g5',
    },
  ]
}

export function getMockScanHistory(): ScanHistory[] {
  return [
    {
      id: 's1',
      scanType: 'manual',
      status: 'completed',
      startedAt: '2024-02-01T10:30:00Z',
      completedAt: '2024-02-01T10:35:00Z',
      totalTransactions: 450,
      duplicatesFound: 12,
      duplicatesResolved: 10,
    },
    {
      id: 's2',
      scanType: 'scheduled',
      status: 'completed',
      startedAt: '2024-01-28T08:00:00Z',
      completedAt: '2024-01-28T08:04:00Z',
      totalTransactions: 380,
      duplicatesFound: 8,
      duplicatesResolved: 8,
    },
    {
      id: 's3',
      scanType: 'manual',
      status: 'completed',
      startedAt: '2024-01-25T14:15:00Z',
      completedAt: '2024-01-25T14:20:00Z',
      totalTransactions: 520,
      duplicatesFound: 15,
      duplicatesResolved: 12,
    },
    {
      id: 's4',
      scanType: 'scheduled',
      status: 'failed',
      startedAt: '2024-01-22T08:00:00Z',
      completedAt: '2024-01-22T08:01:00Z',
      totalTransactions: 0,
      duplicatesFound: 0,
      duplicatesResolved: 0,
      errorMessage: 'QuickBooks API rate limit exceeded',
    },
    {
      id: 's5',
      scanType: 'manual',
      status: 'completed',
      startedAt: '2024-01-20T11:00:00Z',
      completedAt: '2024-01-20T11:06:00Z',
      totalTransactions: 600,
      duplicatesFound: 22,
      duplicatesResolved: 18,
    },
    {
      id: 's6',
      scanType: 'scheduled',
      status: 'completed',
      startedAt: '2024-01-15T08:00:00Z',
      completedAt: '2024-01-15T08:05:00Z',
      totalTransactions: 410,
      duplicatesFound: 6,
      duplicatesResolved: 6,
    },
  ]
}
